### ISSUE TITLE
Segfault in print_cell on malformed input

### ISSUE THREAD

**Issue by hannob** [ThomasDickey/original-mawk#47]
This example crashes mawk, it seems to cause a null pointer deref:
```
BEGIN{OFMT="%n";print .1}
```
Or on the command line:
```
./mawk 'BEGIN{OFMT="%n";print .1}'
```

Here's a stack trace from address sanitizer:
```
==10525==ERROR: AddressSanitizer: SEGV on unknown address 0x000000004959 (pc 0x7fc2044c706c bp 0x7ffc962e32f0 sp 0x7ffc962e2d80 T0)
==10525==The signal is caused by a WRITE memory access.
    #0 0x7fc2044c706b in _IO_vfprintf (/lib64/libc.so.6+0x4906b)
    #1 0x49b56f in __interceptor_vfprintf (/r/mawk/mawk+0x49b56f)
    #2 0x49b64a in __interceptor_fprintf (/r/mawk/mawk+0x49b64a)
    #3 0x540773 in print_cell /f/mawk/mawk-1.3.4-20161107/print.c:66:3
    #4 0x540059 in bi_print /f/mawk/mawk-1.3.4-20161107/print.c:111:6
    #5 0x524f97 in execute /f/mawk/mawk-1.3.4-20161107/execute.c:889:11
    #6 0x523049 in main /f/mawk/mawk-1.3.4-20161107/main.c:99:5
    #7 0x7fc20449e78f in __libc_start_main (/lib64/libc.so.6+0x2078f)
    #8 0x419ed8 in _start (/r/mawk/mawk+0x419ed8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libc.so.6+0x4906b) in _IO_vfprintf
==10525==ABORTING

**Comment by ThomasDickey** [comment]
fixed in [mawk-1.3.4-20161120](http://invisible-island.net/mawk/CHANGES.html#t20161120)
